# Generated by Django 3.2.6 on 2021-09-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_auto_20210912_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shared_item',
            old_name='denied_by',
            new_name='solved_by',
        ),
        migrations.RemoveField(
            model_name='shared_item',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='shared_item',
            name='denied',
        ),
        migrations.RemoveField(
            model_name='shared_item',
            name='denied_at',
        ),
        migrations.AddField(
            model_name='shared_item',
            name='solved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shared_item',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shared_item',
            name='shared_at',
            field=models.DateTimeField(),
        ),
    ]
