# Generated by Django 3.2.6 on 2021-09-21 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='item_for_comm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comm_item', to='capstone.item'),
        ),
    ]
