# Generated by Django 3.2.6 on 2021-09-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0006_alter_comment_item_for_comm'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='file_size',
            field=models.PositiveIntegerField(default=False),
        ),
    ]
