# Generated by Django 3.2.6 on 2021-09-29 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0011_category_valid_extensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='valid_extensions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='format', to='capstone.file_format'),
        ),
    ]
